name: default2
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test2"
      - run: echo '${{ github.event.issue.title }}'
