name: w1
on:
  issues:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch"  ]]; then
            echo ref="${{ inputs.checkout_ref }}" >> $GITHUB_OUTPUT
            echo sha="${{ inputs.checkout_ref }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            if [[ "${{ github.event.workflow_run.head_repository.fork }}" == "true"  ]]; then
              # use the SHA on forks since the head_branch won't exist in the upstream repository
              echo ref="${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
            else
              echo ref="${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
            fi
            echo sha="${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo ref="${{ github.ref }}" >> $GITHUB_OUTPUT
            echo sha="${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "Invalid event type"
            exit 1
          fi
