name: comment
on:
  workflow_run:
    workflows: ["default2"]
    types: [completed]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo "hola"
          echo aaa="${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
