name: Test
on:
  issue_comment:
    types: [created, edited]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub comment context
        id: github_comment_step
        run: echo '${{ toJSON(github.event.comment) }}'

      - uses: ./.github/action
        with:
          test: "addddd"

      - name: Dump GitHub issue context
        id: github_issue_step
        run: echo '${{ toJSON(github.event.issue) }}'
